### ISSUE TITLE
I'm having issues with build.sh 

### ISSUE THREAD

**Issue by jerlegoman** [elliottsj/apple-watch-uikit#2]
While building module 'WatchKit' imported from /Users/JeremyMac/Downloads/apple-watch-uikit-master/AppleWatchUIKit/AppleWatchUIKit WatchKit Extension/InterfaceController.h:9:
While building module 'SceneKit' imported from /Applications/Xcode-beta6.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS3.0.sdk/System/Library/Frameworks/WatchKit.framework/Headers/WKInterfaceSCNScene.h:11:
In file included from <module-includes>:1:
In file included from /Applications/Xcode-beta6.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS3.0.sdk/System/Library/Frameworks/SceneKit.framework/Headers/SceneKit.h:23:
/Applications/Xcode-beta6.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS3.0.sdk/System/Library/Frameworks/SceneKit.framework/Headers/SCNRenderer.h:22:12: note: 'SCNRenderer' has been explicitly marked unavailable here
@interface SCNRenderer : NSObject <SCNSceneRenderer, SCNTechniqueSupport>
           ^
1 error generated.
While building module 'WatchKit' imported from /Users/JeremyMac/Downloads/apple-watch-uikit-master/AppleWatchUIKit/AppleWatchUIKit WatchKit Extension/InterfaceController.h:9:
In file included from <module-includes>:1:
In file included from /Applications/Xcode-beta6.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS3.0.sdk/System/Library/Frameworks/WatchKit.framework/Headers/WatchKit.h:36:
/Applications/Xcode-beta6.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS3.0.sdk/System/Library/Frameworks/WatchKit.framework/Headers/WKInterfaceSCNScene.h:11:9: fatal error: could not build module 'SceneKit'
# import <SceneKit/SceneKit.h>

``` ^
2 errors generated.
In file included from /Users/JeremyMac/Downloads/apple-watch-uikit-master/AppleWatchUIKit/AppleWatchUIKit WatchKit Extension/InterfaceController.m:9:
/Users/JeremyMac/Downloads/apple-watch-uikit-master/AppleWatchUIKit/AppleWatchUIKit WatchKit Extension/InterfaceController.h:9:9: fatal error: could not build module 'WatchKit'
#import <WatchKit/WatchKit.h>
 ~~~~~~~^
3 errors generated.

** BUILD FAILED **

The following build commands failed:
    CompileC /Users/JeremyMac/Library/Developer/Xcode/DerivedData/AppleWatchUIKit-fgobcfxjewwovreesoikkwdwmrwe/Build/Intermediates/AppleWatchUIKit.build/Debug-watchos/AppleWatchUIKit\ WatchKit\ Extension.build/Objects-normal/armv7k/InterfaceController.o AppleWatchUIKit\ WatchKit\ Extension/InterfaceController.m normal armv7k objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

**Comment by elliottsj** [comment]
Looks like you're using Xcode 8 and watchOS 3; I've only tried with watchOS 2 with Xcode 7.

If you're able to get it working with Xcode 8 / watchOS 3; let me know how you did it 😄
