### ISSUE TITLE
about rootViewController problem

### ISSUE THREAD

**Issue by Aw2016** [elliottsj/apple-watch-uikit#4]
Now I have no view on the watch, the error I hope you can look at: Unable to bootstrap_look_up port with name com.trustmobi.AppleWatchUIKit.watchkitapp.watchkitextension.gsEvents: unknown error code (1102),thank you!

**Comment by elliottsj** [comment]
I haven't seen this error. Are you using watchOS 2 and Xcode 7? I've only tested with those versions.

**Comment by Aw2016** [comment]
Thank you, I have been resolved, I use the Watch OS 2 Xcode 8
